### ISSUE TITLE
Linear accuracy script has garbled options

### ISSUE THREAD

**Issue by adamnovak** [vgteam/giraffe-sv-paper#1]
https://github.com/vgteam/giraffe-sv-paper/blob/8e098200c968ae2544530d088e004fe2ccdc012d/scripts/linear_mappers/accuracy_linear.sh#L62

I don't think `-s -sim.gam` is going to work

**Comment by adamnovak** [comment]
@xchang1 Shouldn't it match the other line?

**Comment by xchang1** [comment]
Oh yeah, that's a typo. I'll fix it
