### ISSUE TITLE
Some questions about workflow?

### ISSUE THREAD

**Issue by NMUzhoujun** [vgteam/giraffe-sv-paper#11]
Hello,

As is shown in your workflow, you have converted the bam to the fastq at the first step; then the SV calling, genotyping...

However, why don't we use the fastq file directly. I mean, it will save much time and avoid the problem of genome reference version.

But I am not sure whether it is right or suitable? Will it influence the results?

Hope for you response.
Best,

**Comment by adamnovak** [comment]
It should be perfectly fine to start with a FASTQ file instead; we just happened to have our inputs available most conveniently as BAM files.

**Comment by nmuJUN** [comment]
Thank you very much!

**Comment by nmuJUN** [comment]
Thank you for your response. You all truly have performed a wonderful job!

**Comment by NMUzhoujun** [comment]
Thank you for your response. You all truly have performed an excellent job!
