### ISSUE TITLE
Using \r instead of \t in speed report

### ISSUE THREAD

**Issue by adamnovak** [vgteam/giraffe-sv-paper#2]
There's a `\r` on this line that needs to be a `\t` for this script to actually work right.

https://github.com/vgteam/giraffe-sv-paper/blob/6b49f18bcf4f84cbf5233355ec509492d53b59ec/scripts/giraffe/speed_giraffe.sh#L95

@xchang1 Is this script what you actually ran?

**Comment by xchang1** [comment]
Yeah, this is what I ran, I had to go back and add tabs. I forgot to change the script, sorry

**Comment by xchang1** [comment]
I fixed it
