### ISSUE TITLE
sim error : sample "name" not found in the GBWT index`

### ISSUE THREAD

**Issue by Chenglin20170390** [vgteam/giraffe-sv-paper#3]
Hi，
   I simulate reads from vg for testing my species alignment based on your giraffe-sv-paper script. However, I get an error below
command : 
`vg sim -r -n 1000 -a -s 12345 -p 570 -v 165 -i 0.00029 -x x.xg -g x.gbwt --sample-name C151 --ploidy-regex "JTFH.*:0,KN70.*:0,Y:0,chrY_.*:0,chrEBV:0,.*:2" | vg annotate -p -x x.xg -a - > sim.gam`
`[vg sim] error: sample "C151" not found in the GBWT index`  

if I  remove the -g option for simulate reads from vg, it's worked, the result shown as below(not remove segmental duplications from  prep section since my species do not have  segmental duplications bed file , and I used conda to install vg)
![image](https://user-images.githubusercontent.com/33062118/118071947-61813700-b3db-11eb-99e3-8742a847f9ea.png)

So, do you have any suggestion to get the ROC figure as the same good as your giraffe articles?
Many thanks for your help~

**Comment by jltsiren** [comment]
Does the GBWT contain sample names, and is the sample name correct? `vg gbwt -M x.gbwt` should tell if there are sample names, and `vg gbwt -S -L x.gbwt` should list the names.

If there are no sample names, how did you build the GBWT? VG tools should always store the metadata, but some standalone tools in the GBWT and GBWTGraph repositories do not.

**Comment by Chenglin20170390** [comment]
Hi Jouni Siren，

    Many thanks for your help, the problem solved perfectly~~~ thanks
