### ISSUE TITLE
Reference bias issue

### ISSUE THREAD

**Issue by Chenglin20170390** [vgteam/giraffe-sv-paper#4]
Hi, I would like to test whether VG can efficiently reduce reference bias in potato as good as your team did in human genome analysis, thus I repeat the giraffe article with the following commands, but the results show giraffe is a little good than bwa, but not very good as your team did. Is it my command problem or my input vcf problem to construct the variation graph?  do you have any suggestions?
The command for filtering input vcf from gatk variation calling
```
vcftools --gzvcf 44.raw.vcf.gz --minQ 30 --recode --minDP 3 --recode-INFO-all --out 44.snp.indel.vcf
bgzip 44.snp.indel.vcf
bcftools tabix 44.snp.indel.vcf.gz
```
Command for VG reference bias
```
#vg construct
ref=DM.fa
name=DM
vcf=44.snp.indel.vcf.gz
vg construct -r $ref -t 20 -v $vcf -a > x.$name.vg
vg index -x x.$name.xg -g x.$name.gcsa -k 16 -t 100  x.$name.vg

##gbwt
vg gbwt -p -g output.$name.gg -o output.$name.gbwt -E -x x.$name.xg 
vg minimizer -t 20 -p -i output.$name.min -g output.$name.gbwt -G output.$name.gg
vg snarls x.$name.xg >x.$name.snarls
vg index -j $name.dist -s x.$name.snarls x.$name.vg 

#real data for reference bias
f1=02_data/PG5002/s5002_HGVCKALXX_L1_1.clean.fq.gz
f2=02_data/PG5002/s5002_HGVCKALXX_L1_2.clean.fq.gz

#giraffe
vg giraffe -H output.$name.gbwt -g output.$name.gg -m output.$name.min -d $name.dist -f $f1 -f $f2 -t 24 | vg surject -x x.$name.xg -b -t 24 - > mapped.giraffe.bam
samtools sort mapped.giraffe.bam -@ 20 > mapped.sorted.giraffe.bam
samtools index -@ 20 mapped.sorted.giraffe.bam
#bwa
bwa mem -t 24 -p $ref $f1 $f2 > mapped.bwa.bam
samtools sort mapped.bwa.bam -@ 20 > mapped.sorted.bwa.bam
samtools index -@ 20 mapped.sorted.bwa.bam

bcftools mpileup --threads 20 -f $ref -E -a DP -a SP -a ADF -a ADR -a AD  -O u  mapped.sorted.giraffe.bam | bcftools call --threads 20 -m -o calls.giraffe.vcf.gz -O z -v
bcftools mpileup --threads 20 -f $ref -E -a DP -a SP -a ADF -a ADR -a AD  -O u  mapped.sorted.bwa.bam | bcftools call --threads 20 -m -o calls.bwa.vcf.gz -O z -v

bcftools sort -O z calls.bwa.vcf.gz >calls.bwa.sorted.vcf.gz
bcftools sort -O z calls.giraffe.vcf.gz >calls.gif.sorted.vcf.gz

bcftools index -f calls.bwa.sorted.vcf.gz
bcftools index -f calls.gif.sorted.vcf.gz

# vi  rename bam name to mapped.sorted.bam
bcftools merge calls.gif.sorted.vcf.gz calls.bwa.sorted.vcf.gz -O z > all_calls.vcf.gz

python3 plot_allele_bia.py  all_calls.vcf allel_bias.svg
```
The resulting figure.
![image](https://user-images.githubusercontent.com/33062118/120264209-db685a00-c2cf-11eb-83e4-894af223ea5f.png)

**Comment by jeizenga** [comment]
@xchang1 Do you have a link to the pipeline we used to measure reference allele bias?

**Comment by xchang1** [comment]
This looks like it's following what I did, the allele balance part looks correct to me.

In your gbwt construction step, you used `-E` instead of using a vcf.  I think using `-E` will produce a gbwt with only the reference path. Since you have an input vcf, you should use it when constructing the gbwt like this:
```vg gbwt -p -g output.$name.gg -o output.$name.gbwt -v $vcf -x x.$name.xg ```
If your vcf has a lot of samples in it (e.g., ours had 5000 which was too many), you can downsample it as well
```vg gbwt -p -g output.sampled.gg -o output.sampled.gbwt -x ix.$name.xg -n 64 -l output.$name.gbwt```
https://github.com/vgteam/giraffe-sv-paper/blob/master/scripts/indexing/07_make_1000GPlons_GRCh38_cover_gbwts.sh#L32. 
We used `-n 64` (meaning that we generated 64 artificial haplotypes for the sampled gbwt) but it might be different for potato

**Comment by Chenglin20170390** [comment]
Hi xchang1 and VG teams,
      Many thanks for your help.
     After using the first command that you recommended(`vg gbwt -p -g output.$name.gg -o output.$name.gbwt -v $vcf -x x.$name.xg`) and  second command  for downsample (`vg gbwt -p -g output.sampled.gg -o output.sampled.gbwt -x x.$name.xg -n 64 -l output.$name.gbwt`). there is an error in`vg giraffe -H $name.gbwt -g $name.gg -m $name.min -d $name.dist -f $f1 -f $f2 -t 24 | vg surject -x $name.xg -b -t 24 - > mapped.giraffe.bam`
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_sQoadz/stacktrace.txt
Please include the stack trace file in your bug report!
```
stack file
```
Crash report for vg v1.32.0 "Sedlo"
Stack trace (most recent call last) in thread 671063:
#16   Object "", at 0xffffffffffffffff, in 
#15   Object "", at 0x1e11e82, in 
#14   Object "", at 0x127cb08, in 
#13   Object "", at 0x1d5aa8d, in 
#12   Object "", at 0xb09873, in 
#11   Object "", at 0x1d5d367, in 
#10   Object "", at 0x1d54a2b, in 
#9    Object "", at 0xb091f1, in 
#8    Object "", at 0x4bb407, in 
#7    Object "", at 0x1d6b189, in 
#6    Object "", at 0x1d6a79a, in 
#5    Object "", at 0x1ca92c3, in 
#4    Object "", at 0x1d490c8, in 
#3    Object "", at 0x1ca961b, in 
#2    Object "", at 0x1caac19, in 
#1    Object "", at 0x577953, in 
#0    Object "", at 0x127feeb, in 
```

**Comment by xchang1** [comment]
Hm that's going to be a hard one to debug without a stack trace. Can you share your data so we can reproduce this? 
The gbwt commands I sent might be wrong too. @jltsiren do you have any suggestions?

**Comment by jltsiren** [comment]
Did you rebuild the minimizer index for the GBWT you use in Giraffe? If the index is based on another GBWT, it could contain seeds in nodes that do not exist in the graph Giraffe is using.

Does the crash happen in `vg giraffe` or `vg surject` if you run them as separate commands?

**Comment by xchang1** [comment]
Oh that's a good point, thanks Jouni. Sorry, I forgot to mention that you'd have to rebuild the minimizer index.
When you build the minimizer index, you can also include `-d $name.dist` (you don't need to rebuild the distance index). This won't change the accuracy at all but it will make giraffe faster

**Comment by Chenglin20170390** [comment]
Hi， many thanks for your help, how to share my data ? I pick up chr12 (60M) from my data and test with the different commands, but it still has error or warning.
1）For Error with index -L;
```
name=chr12
ref=chr12.fa
vcf=chr12.sort.filt2.vcf.gz
tmp=/vol3/agis/
vg construct -r $ref -t 20 -v $vcf -a > $name.vg
vg index -t 200 -p -L -b $tmp  -j $name.dist -x $name.xg $name.vg
vg snarls $name.xg >$name.snarls
vg gbwt -p -g $name.gg -o $name.gbwt -v $vcf -x $name.xg 

vg minimizer -t 20 -p -i $name.min -d $name.dist -g $name.gbwt -G $name.gg
vg giraffe -H $name.gbwt -g $name.gg -m $name.min -d $name.dist -f $f1 -f $f2 -t 24 | vg surject -x $name.xg -b -t 24 - > mapped.giraffe.bam
warning[vg::giraffe]: Encountered 100000 ambiguously-paired reads before finding enough
                      unambiguously-paired reads to learn fragment length distribution. Are you sure
                      your reads are paired and your graph is not a hairball?
warning[vg::giraffe]: Finalizing fragment length distribution before reaching maximum sample size
                      mapped 458 reads single ended with 100000 pairs of reads left unmapped
                      mean: 0, stdev: 1
warning[vg::giraffe]: Cannot cluster reads with a fragment distance smaller than read distance
                      Fragment length distribution: mean=0, stdev=1
                      Fragment distance limit: 2, read distance limit: 200
warning[vg::giraffe]: Falling back on single-end mapping
terminate called recursively
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug
```
2)  for index with -E , it shows warnings but can generate bam and then call vcf file :
```
vg construct -r $ref -t 100 -v $vcf -a > x.$name.vg
vg index -x $name.xg -k 16 -t 100 -E -b $tem $name.vg
vg gbwt -p -g $name.gg -o $name.gbwt -v $vcf -x $name.xg
vg gbwt -p -g $name.gg -o $name.gbwt -x $name.xg -n 64 -l $name.gbwt
vg snarls $name.xg >$name.snarls
vg index -j $name.dist -s $name.snarls $name.vg
vg minimizer -t 20 -p -i $name.min -d $name.dist -g $name.gbwt -G $name.gg
vg giraffe -H $name.gbwt -g $name.gg -m $name.min -d $name.dist -f $f1 -f $f2 -t 24 | vg surject -x $name.xg -b -t 24 - > mapped.giraffe.bam
warning[vg::giraffe]: Encountered 100000 ambiguously-paired reads before finding enough
                      unambiguously-paired reads to learn fragment length distribution. Are you sure
                      your reads are paired and your graph is not a hairball?
warning[vg::giraffe]: Finalizing fragment length distribution before reaching maximum sample size
                      mapped 661 reads single ended with 100000 pairs of reads left unmapped
                      mean: 0, stdev: 1
warning[vg::giraffe]: Cannot cluster reads with a fragment distance smaller than read distance
                      Fragment length distribution: mean=0, stdev=1
                      Fragment distance limit: 2, read distance limit: 200
warning[vg::giraffe]: Falling back on single-end mapping

```
for @jltsiren 's question, I have rebuilt the minimizer index, but still, get error,  and it crash at vg giraffe

I will try toil-vg to make a graph that you used in the giraffe article and different commands and say it's will work or not for my species.

**Comment by adamnovak** [comment]
@xchang1 Doesn't the distance index want a snarls file that includes trivial snarls (`-T` added to the `vg snarls` command)? I recall seeing crashes when the distance index was built without them.

I also notice @Chenglin20170390 that you aren't using the `--force-phasing` and `--discard-overlaps` options to the command to generate the GBWT from the VCF; we almost always use these because VCF files often specify haplotypes which aren't self-consistent, which can produce a bad GBWT. That wouldn't be expected to crash Giraffe, but maybe it's triggering a bug.

Rather than messing around with all the little flags that need to be exactly right, we now recommend letting `vg autoindex` do all the graph construction and indexing for you, as described [in this tutorial](https://github.com/vgteam/vg/wiki/Mapping-short-reads-with-Giraffe). You would want to get vg v1.33 or later, make sure to delete `${name}.*`, and do something like:

```
vg autoindex --workflow giraffe -r $ref -v $vcf -p $name
```

This will do everything in `vg construct`, `vg index`, `vg gbwt`, `vg snarls`, and `vg minimizer` for you, and leave behind the indexes Giraffe needs as `$name.*`. Then you can just pass them along to Giraffe with the appropriate Giraffe flags for each file type.

Also, if you're mapping whole-genome reads to just one chromosome in this test, Giraffe won't be able to learn the fragment length distribution very well, because most read pairs aren't actually from the graph you are using and won't map well. I think we might have a bug where Giraffe will crash in a not very graceful way when it can't learn the distribution; it tries to use its not-very-sensible defaults, which don't work. You would want to map single-ended (one FASTQ at a time), or pass `--fragment-mean` and `--fragment-stdev` so it has a fragment length distribution to use.

**Comment by Chenglin20170390** [comment]
Many  thanks for your patient explanation as well as the  development of  such a convenient  tool `vg autoindex`,  Now, I know better about this useful tookit. After updating vg tookit from conda(v1.33.0), I can success run the autoindex and generate gam file from `vg giraffe -H $name.giraffe.gbwt -g $name.gg -m $name.min -d $name.dist  -f $f1 -t 24 >$name.gam`.
    
For my intention, I would like to test vg reference bias analysis, so I need to convert gam to bam by `vg surject -x $name.xg -b -t 24 - > mapped.giraffe.bam` . However, this step need a $name.xg file,  `vg autoindex`only leave behind the indexes Giraffe needs as you said $name.*($name.min, $name.dist,$name.gg,$name.giraffe.gbwt).
  
I have try different command to generate `$name.vg` and `$name.xg` and then convert $name.gam to `$name.bam`, but all failed at the converting step. So, can you tell me the correct way to make a $name.vg and $name. xg to correlation with the output of `vg autoindex` ?  

Many  thanks (*^▽^*)

**Comment by adamnovak** [comment]
If you give Giraffe `-o BAM` it will do the surject step for you. I think then it might need the XG index provided to it as well, though.

@jeizenga might have an idea for how we ought to solve this problem in general (maybe we should make the XG an output in the default Giraffe indexing set?), but if you give `vg autoindex` the undocumented `-R XG` option, it will save the xg for you along with the other files. I'm not sure if it is deterministic enough that you could run it a second time and use the resulting XG with the GAM from the first set of indexes, or if you would have to then remap with the index set for which you saved the GAM.

In the current in-development vg, you should be able to use use `vg convert $name.gg --gbwt-in $name.gbwt --xg-out >$name.xg` to make the XG from the GG and GBWT, but that might not have been possible in the 1.33.0 release. You also might need `--ref-sample` and the GBWT sample name of the GBWT sample name your primary reference is using, to get paths for surject to make the BAM on.

Does that help?

**Comment by jeizenga** [comment]
Adding the `-R XG` should be fine if you want to also produce a .xg file. It's probably also worth noting that in the next release version, `vg autoindex` will be changed to produce a .gbz file instead of a paired .gg and .gbwt file. The .gbz file is semantically equivalent, and the `vg giraffe` interface has been updated to support .gbz input.

**Comment by Chenglin20170390** [comment]
Many thanks for your help, I test with chr12, the commands `vg autoindex --workflow giraffe -r $ref -v $vcf -p $name -R XG` are working for me. However, although I can see more variations in the giraffe mapping result (2.9 million) than the bwa mapping result (1.9 million),the reference bias results still can not show the big difference...

I may test with a different sample or all chr. Many thanks for your help. I believe vg is a very useful toolkit, and I will continue to pay attention to it.

![image](https://user-images.githubusercontent.com/33062118/122165188-6fc6e500-ceaa-11eb-8ae5-e6a96660c59b.png)

**Comment by Chenglin20170390** [comment]
Hi vg team, a good news,  after try whole chromosome (not just chr12), I can get a nice figure to show the reduction of reference bias analysis from vg.  I think it's because the chromosome  12 is a bit strange in potatoes (also  confirmed from some other analyses in chr12)
Many thanks for your help~~
![image](https://user-images.githubusercontent.com/33062118/122718449-8b156400-d29f-11eb-9d11-e1c5d84c0409.png)
